/*==============================================================*/
/* Table: MTXTB007_TAREFA_MENSAGEM                         */
/*==============================================================*/
ALTER TABLE MTX.MTXTB007_TAREFA_MENSAGEM ADD NO_CAMPO_RETORNO VARCHAR2(200) NOT NULL;
ALTER TABLE MTX.MTXTB007_TAREFA_MENSAGEM ADD NU_VERSAO_TAREFA_012 NUMBER(3) NOT NULL;
ALTER TABLE MTX.MTXTB007_TAREFA_MENSAGEM RENAME COLUMN NU_TAREFA_002 TO NU_TAREFA_012;
ALTER TABLE MTX.MTXTB007_TAREFA_MENSAGEM DROP CONSTRAINT FK_MTXTB007_MTXTB002;


ALTER TABLE MTXTB007_TAREFA_MENSAGEM
   ADD CONSTRAINT FK_MTXTB007_MTXTB012 FOREIGN KEY (NU_TAREFA_012, NU_VERSAO_TAREFA_012)
      REFERENCES MTXTB012_VERSAO_TAREFA (NU_TAREFA_002, NU_VERSAO_TAREFA);