-- ******************* SERVICOS  *********************** --
INSERT INTO MTX.MTXTB001_SERVICO (NU_SERVICO, NO_SERVICO, NO_SERVICO_BARRAMENTO, NO_OPERACAO_BARRAMENTO, IC_SITUACAO_SERVICO, IC_CONFIRMACAO_TRANSACAO, IC_TIPO_SERVICO, NO_CONEXAO, QT_SGNDO_LMTE_RESPOSTA, NO_FILA_REQUISICAO, NO_FILA_RESPOSTA, DH_ATUALIZACAO) VALUES(110026,'Segunda Via Lista Transa��es','consulta_lista_transacoes','CONSULTA_LISTA_TRANSACOES',1,0,6, '-', 0, '-', '-', SYSDATE);
INSERT INTO MTX.MTXTB001_SERVICO (NU_SERVICO, NO_SERVICO, NO_SERVICO_BARRAMENTO, NO_OPERACAO_BARRAMENTO, IC_SITUACAO_SERVICO, IC_CONFIRMACAO_TRANSACAO, IC_TIPO_SERVICO, NO_CONEXAO, QT_SGNDO_LMTE_RESPOSTA, NO_FILA_REQUISICAO, NO_FILA_RESPOSTA, DH_ATUALIZACAO) VALUES(110027,'Segunda Via Detalhe Transa��o','detalhe_transacao','DETALHE_TRANSACAO',1,0,6, '-', 0, '-', '-', SYSDATE);


-- ******************* VERSAO SERVICOS  *********************** --
INSERT INTO MTX.MTXTB011_VERSAO_SERVICO (NU_SERVICO_001, NU_VERSAO_SERVICO, CO_VERSAO_BARRAMENTO, IC_SERVICO_MIGRADO, DE_XSD_REQUISICAO, DE_XSLT_REQUISICAO, DE_XSD_RESPOSTA, DE_XSLT_RESPOSTA, DH_ATUALIZACAO, IC_STCO_VRSO_SRVCO) VALUES(110026,1, '1', 0, 'validacao_entradas/SIMTX_TYPES/V1/Segunda_Via_Consulta_Lista_Transacoes_Canal.xsd','requisicao_simtx.xsl','validacao_entradas/SIMTX_TYPES/V1/Segunda_Via_Consulta_Lista_Transacoes_Canal.xsd','servico/V1/segundaViaListaTransacoes_Resp.xsl',SYSDATE,1);
INSERT INTO MTX.MTXTB011_VERSAO_SERVICO (NU_SERVICO_001, NU_VERSAO_SERVICO, CO_VERSAO_BARRAMENTO, IC_SERVICO_MIGRADO, DE_XSD_REQUISICAO, DE_XSLT_REQUISICAO, DE_XSD_RESPOSTA, DE_XSLT_RESPOSTA, DH_ATUALIZACAO, IC_STCO_VRSO_SRVCO) VALUES(110027,1, '1', 0, 'validacao_entradas/SIMTX_TYPES/V1/Segunda_Via_Detalhe_Transacao_Canal.xsd','requisicao_simtx.xsl','validacao_entradas/SIMTX_TYPES/V1/Segunda_Via_Detalhe_Transacao_Canal.xsd','servico/V1/segundaViaDetalheTransacao_Resp.xsl',SYSDATE,1);


-- ******************* TAREFAS  *********************** --
INSERT INTO MTX.MTXTB002_TAREFA (NU_TAREFA, NO_TAREFA, NO_SERVICO_BARRAMENTO, NO_OPERACAO_BARRAMENTO, IC_TAREFA_FINANCEIRA, IC_TIPO_TAREFA, DH_ATUALIZACAO) VALUES(100048,'Lista Transações (Segunda Via)','consulta_lista_transacoes','CONSULTA_LISTA_TRANSACOES',0,2,SYSDATE);
INSERT INTO MTX.MTXTB002_TAREFA (NU_TAREFA, NO_TAREFA, NO_SERVICO_BARRAMENTO, NO_OPERACAO_BARRAMENTO, IC_TAREFA_FINANCEIRA, IC_TIPO_TAREFA, DH_ATUALIZACAO) VALUES(100049,'Detalhe Transação (Segunda Via)','detalhe_transacao','DETALHE_TRANSACAO',0,2,SYSDATE);


-- ******************* VERSAO TAREFAS  *********************** --
INSERT INTO MTX.MTXTB012_VERSAO_TAREFA (NU_TAREFA_002, NU_VERSAO_TAREFA, IC_SITUACAO, IC_DESFAZIMENTO, IC_PARALELISMO, IC_ASSINCRONO, DE_XSD_REQUISICAO, DE_XSLT_REQUISICAO,DE_XSD_RESPOSTA, DE_XSLT_RESPOSTA, DE_XSLT_PARAMETRO, DH_ATUALIZACAO)VALUES(100048,1,1,0,0,0,'validacao_entradas/SICCO/NEGOCIAL/V1/Segunda_Via_Consulta_Lista_Transacoes.xsd','negocial/V1/segundaViaListaTransacoes_Req.xsl','validacao_entradas/SICCO/NEGOCIAL/V1/Segunda_Via_Consulta_Lista_Transacoes.xsd','negocial/V1/segundaViaListaTransacoes_Resp.xsl','',SYSDATE);
INSERT INTO MTX.MTXTB012_VERSAO_TAREFA (NU_TAREFA_002, NU_VERSAO_TAREFA, IC_SITUACAO, IC_DESFAZIMENTO, IC_PARALELISMO, IC_ASSINCRONO, DE_XSD_REQUISICAO, DE_XSLT_REQUISICAO,DE_XSD_RESPOSTA, DE_XSLT_RESPOSTA, DE_XSLT_PARAMETRO, DH_ATUALIZACAO)VALUES(100049,1,1,0,0,0,'validacao_entradas/SICCO/NEGOCIAL/V1/Segunda_Via_Detalhe_Transacao.xsd','negocial/V1/segundaViaDetalheTransacao_Req.xsl','validacao_entradas/SICCO/NEGOCIAL/V1/Segunda_Via_Detalhe_Transacao.xsd','negocial/V1/segundaViaDetalheTransacao_Resp.xsl','',SYSDATE);


-- ******************* TAREFA X FILA  *********************** --
INSERT INTO MTX.MTXTB024_TAREFA_FILA (NU_TAREFA_012, NU_VERSAO_TAREFA_012, SG_SISTEMA_CORPORATIVO, NO_FILA_REQUISICAO, QT_SGNDO_LMTE_REQUISICAO, NO_FILA_RESPOSTA, QT_SGNDO_LMTE_RESPOSTA, NO_MODO_INTEGRACAO, NO_RECURSO, QT_TEMPO_ESPERA,  NO_CONEXAO) VALUES (100048, 1, 'SICCO', 'java:jboss/jms/req_segunda_via', 5000, 'java:jboss/jms/rsp_valida_assinatura', 5000, '-', '-', 0, 'java:jboss/jms/SimtxQueueConnectionFactorySIMTX');
INSERT INTO MTX.MTXTB024_TAREFA_FILA (NU_TAREFA_012, NU_VERSAO_TAREFA_012, SG_SISTEMA_CORPORATIVO, NO_FILA_REQUISICAO, QT_SGNDO_LMTE_REQUISICAO, NO_FILA_RESPOSTA, QT_SGNDO_LMTE_RESPOSTA, NO_MODO_INTEGRACAO, NO_RECURSO, QT_TEMPO_ESPERA,  NO_CONEXAO) VALUES (100049, 1, 'SICCO', 'java:jboss/jms/req_segunda_via', 5000, 'java:jboss/jms/rsp_valida_assinatura', 5000, '-', '-', 0, 'java:jboss/jms/SimtxQueueConnectionFactorySIMTX');


-- ******************* SERVICO X TAREFA  *********************** --
INSERT INTO MTX.MTXTB003_SERVICO_TAREFA (NU_SERVICO_011, NU_VERSAO_SERVICO_011, NU_TAREFA_012, NU_VERSAO_TAREFA_012, NU_SEQUENCIA_EXECUCAO, IC_SITUACAO, IC_IMPEDIMENTO, DE_XSLT_NOVA_TAREFA) VALUES(110026,1,100025,1,1,1,1, '');
INSERT INTO MTX.MTXTB003_SERVICO_TAREFA (NU_SERVICO_011, NU_VERSAO_SERVICO_011, NU_TAREFA_012, NU_VERSAO_TAREFA_012, NU_SEQUENCIA_EXECUCAO, IC_SITUACAO, IC_IMPEDIMENTO, DE_XSLT_NOVA_TAREFA) VALUES(110026,1,100029,1,2,1,1, '');
INSERT INTO MTX.MTXTB003_SERVICO_TAREFA (NU_SERVICO_011, NU_VERSAO_SERVICO_011, NU_TAREFA_012, NU_VERSAO_TAREFA_012, NU_SEQUENCIA_EXECUCAO, IC_SITUACAO, IC_IMPEDIMENTO, DE_XSLT_NOVA_TAREFA) VALUES(110026,1,100048,1,3,1,1, '');
INSERT INTO MTX.MTXTB003_SERVICO_TAREFA (NU_SERVICO_011, NU_VERSAO_SERVICO_011, NU_TAREFA_012, NU_VERSAO_TAREFA_012, NU_SEQUENCIA_EXECUCAO, IC_SITUACAO, IC_IMPEDIMENTO, DE_XSLT_NOVA_TAREFA) VALUES(110027,1,100025,1,1,1,1, '');
INSERT INTO MTX.MTXTB003_SERVICO_TAREFA (NU_SERVICO_011, NU_VERSAO_SERVICO_011, NU_TAREFA_012, NU_VERSAO_TAREFA_012, NU_SEQUENCIA_EXECUCAO, IC_SITUACAO, IC_IMPEDIMENTO, DE_XSLT_NOVA_TAREFA) VALUES(110027,1,100029,1,2,1,1, '');
INSERT INTO MTX.MTXTB003_SERVICO_TAREFA (NU_SERVICO_011, NU_VERSAO_SERVICO_011, NU_TAREFA_012, NU_VERSAO_TAREFA_012, NU_SEQUENCIA_EXECUCAO, IC_SITUACAO, IC_IMPEDIMENTO, DE_XSLT_NOVA_TAREFA) VALUES(110027,1,100049,1,3,1,1, '');


-- ******************* SERVICO X CANAL  *********************** --
INSERT INTO MTX.MTXTB005_SERVICO_CANAL (NU_SERVICO_001, NU_CANAL_004, IC_STCO_SRVCO_CANAL) VALUES(110026,110,1);
INSERT INTO MTX.MTXTB005_SERVICO_CANAL (NU_SERVICO_001, NU_CANAL_004, IC_STCO_SRVCO_CANAL) VALUES(110027,110,1);


-- ******************* PARAMETRO X SERVICO X CANAL  *********************** --
INSERT INTO MTX.MTXTB013_PRMTO_SRVCO_CANAL (NU_PARAMETRO, NU_SERVICO_005, NU_CANAL_005, HH_LIMITE_INICIO, HH_LIMITE_FIM, DT_INCO_SLCTO_SRVCO, DT_FIM_SLCTO_SRVCO, VR_MNMO_SLCTO_SRVCO, VR_MXMO_SLCTO_SRVCO, DH_ATUALIZACAO) VALUES(103,110026,110,TO_DATE('01/01/2015 08:02:44', 'dd/mm/yyyy hh24:mi:ss'),TO_DATE('01/01/2017 21:02:44', 'dd/mm/yyyy hh24:mi:ss'),TO_DATE('01/01/2015 08:02:44', 'dd/mm/yyyy hh24:mi:ss'),TO_DATE('01/01/2018 08:02:44', 'dd/mm/yyyy hh24:mi:ss'),1,1000,SYSDATE);
INSERT INTO MTX.MTXTB013_PRMTO_SRVCO_CANAL (NU_PARAMETRO, NU_SERVICO_005, NU_CANAL_005, HH_LIMITE_INICIO, HH_LIMITE_FIM, DT_INCO_SLCTO_SRVCO, DT_FIM_SLCTO_SRVCO, VR_MNMO_SLCTO_SRVCO, VR_MXMO_SLCTO_SRVCO, DH_ATUALIZACAO) VALUES(104,110027,110,TO_DATE('01/01/2015 08:02:44', 'dd/mm/yyyy hh24:mi:ss'),TO_DATE('01/01/2017 21:02:44', 'dd/mm/yyyy hh24:mi:ss'),TO_DATE('01/01/2015 08:02:44', 'dd/mm/yyyy hh24:mi:ss'),TO_DATE('01/01/2018 08:02:44', 'dd/mm/yyyy hh24:mi:ss'),1,1000,SYSDATE);


-- ******************* SERVICO X TAREFA X CANAL  *********************** --
INSERT INTO MTX.MTXTB020_SRVCO_TARFA_CANAL (NU_SERVICO_003, NU_VERSAO_SERVICO_003, NU_TAREFA_003, NU_VERSAO_TAREFA_003, NU_CANAL_004) VALUES(110026,1,100025,1,110);
INSERT INTO MTX.MTXTB020_SRVCO_TARFA_CANAL (NU_SERVICO_003, NU_VERSAO_SERVICO_003, NU_TAREFA_003, NU_VERSAO_TAREFA_003, NU_CANAL_004) VALUES(110026,1,100029,1,110);
INSERT INTO MTX.MTXTB020_SRVCO_TARFA_CANAL (NU_SERVICO_003, NU_VERSAO_SERVICO_003, NU_TAREFA_003, NU_VERSAO_TAREFA_003, NU_CANAL_004) VALUES(110026,1,100048,1,110);
INSERT INTO MTX.MTXTB020_SRVCO_TARFA_CANAL (NU_SERVICO_003, NU_VERSAO_SERVICO_003, NU_TAREFA_003, NU_VERSAO_TAREFA_003, NU_CANAL_004) VALUES(110027,1,100025,1,110);
INSERT INTO MTX.MTXTB020_SRVCO_TARFA_CANAL (NU_SERVICO_003, NU_VERSAO_SERVICO_003, NU_TAREFA_003, NU_VERSAO_TAREFA_003, NU_CANAL_004) VALUES(110027,1,100029,1,110);
INSERT INTO MTX.MTXTB020_SRVCO_TARFA_CANAL (NU_SERVICO_003, NU_VERSAO_SERVICO_003, NU_TAREFA_003, NU_VERSAO_TAREFA_003, NU_CANAL_004) VALUES(110027,1,100049,1,110);


-- ******************* MEIO ENTRADA  *********************** --
INSERT INTO MTX.MTXTB008_MEIO_ENTRADA (NU_MEIO_ENTRADA, NO_MEIO_ENTRADA, IC_SITUACAO) VALUES(4,'#VALIDA_CARTAO#VALIDA_SENHA',1);


-- ******************* VERSAO TAREFA X MEIO ENTRADA  *********************** --
INSERT INTO MTX.MTXTB010_VRSO_TARFA_MEIO_ENTRA (NU_TAREFA_012, NU_VERSAO_TAREFA_012, NU_MEIO_ENTRADA_008, IC_SITUACAO) VALUES(100025,1,4,1);
INSERT INTO MTX.MTXTB010_VRSO_TARFA_MEIO_ENTRA (NU_TAREFA_012, NU_VERSAO_TAREFA_012, NU_MEIO_ENTRADA_008, IC_SITUACAO) VALUES(100029,1,4,1);


-- ******************* VERSAO MEIO ENTRADA X SERVICO  *********************** --
INSERT INTO MTX.MTXTB018_VRSO_MEIO_ENTRA_SRVCO (NU_MEIO_ENTRADA_008, NU_SERVICO_011, NU_VERSAO_SERVICO_011, IC_SITUACAO, DH_ATUALIZACAO) VALUES(4,110026,1,1,SYSDATE);
INSERT INTO MTX.MTXTB018_VRSO_MEIO_ENTRA_SRVCO (NU_MEIO_ENTRADA_008, NU_SERVICO_011, NU_VERSAO_SERVICO_011, IC_SITUACAO, DH_ATUALIZACAO) VALUES(4,110027,1,1,SYSDATE);


