package br.gov.caixa.simtx.persistencia.constante;

public enum MensagemRetorno {
	SUCESSO(1L),
	TIMEOUT(9L),
	NSU_NAO_GERADO(10L),
	CANAL_INEXISTENTE(11L),
	VERSAO_SERVICO_INEXISTENTE(12L),
	LEIAUTE_MENSAGEM_INVALIDA(13L),
	SERVICO_INATIVO(14L),
	VERSAO_SERVICO_INATIVA(15L),
	CANAL_ATENDIMENTO_INATIVO(16L),
	SERVICO_INEXISTENTE_PARA_CANAL(17L),
	SERVICO_INATIVO_CANAL(18L),
	HORARIO_INVALIDO_TRANSACAO(19L),
	DATA_INVALIDA_TRANSACAO(20L),
	VALOR_INFERIOR_VALOR_MINIMO(21L),
	VALOR_SUPERIOR_VALOR_MAXIMO(22L),
	MEIO_ENTRADA_INEXISTENTE(23L),
	MEIO_ENTRADA_INATIVO(24L),
	MEIO_ENTRADA_INEXISTENTE_SERVICO(25L),
	MEIO_ENTRADA_INATIVO_SERVICO(26L),
	LEIAUTE_MENSAGEM_RESPOSTA_INVALIDO(27L),
	ERRO_GRAVACAO_TRANSACAO(28L),
	ERRO_INTERNO(29L),
	ERRO_GRAVAR_ASSINATURA_MULTIPLA(30L),
	ERRO_RECUPERAR_DETALHE_ASSINATURA_MULTIPLA(31L),
	ERRO_RECUPERAR_TAREFAS(32L),
	DATA_AGENDAMENTO_MAIOR_PERMITIDO(33L),
	NAO_ENCONTROU_RESULTADOS(166L),
	DATA_REFERENCIA_INVALIDA(167L),
	DATA_CANAL_POSTERIOR_DATA_ATUAL(168L),
	AGENDAMENTO_NAO_ENCONTRADO(170L),
	CODIGO_RETORNO_IMPEDITIVO_AGENDAMENTO(173L),
	AGENDAMENTO_JA_CANCELADO(174L),
	AGENDAMENTO_JA_EFETIVADO(175L),
	WS_LAYOUT_INVALIDO(157L),
	WS_NAO_RECUPEROU_DADOS_MATRIZ(178L),
	WS1_NAO_RECEBER_BOLETO(158L),
	WS2_BOLETO_VENCIDO(159L),
	WS2_DATA_POSTERIOR_VENCIMENTO(160L),
	WS2_VALOR_PAGO_DIF_VALOR_CALCULADO(161L),
	WS2_VALOR_NAO_ESTA_MINIMO_MAXIMO(162L),
	WS2_VALOR_PAGO_MENOR_MINIMO(163L),
	WS2_VALOR_PAGAR_ZERADO(180L),
	WS2_DATA_PAGAMENTO_ANTERIOR_ATUAL(179L),
	WS2_NAO_ACEITA_PAGAMENTO_CONTINGENCIA(181L),
	WS2_VALOR_PAGTO_CONTINGENCIA_NAO_ATENDE_PREMISSAS(182L),
	WS2_VALOR_PAGAR_MAIOR_VALOR_BARRA(191L),
	NAO_PERMITE_AGENDAMENTO_CONTINGENCIA_CIP(183L),
	NAO_PERMITE_AGENDAMENTO_MODELO_CALCULO_3(184L),
	ERRO_QUEBRAR_CODIGO_BARRAS(185L),
	CODIGO_BARRAS_INVALIDO(186L),
	ERRO_VERIFICAR_DATA_BASE_NOVA(187L),
	FATOR_VENCIMENTO_INVALIDO(188L),
	ERRO_ATUALIZA_DATA_BASE_ATUAL(189L),
	ERRO_ATUALIZA_DATA_BASE_NOVA(190L);
	

	private MensagemRetorno(Long codigo) {
		this.codigo = codigo;
	}
	
	private Long codigo;

	public Long getCodigo() {
		return codigo;
	}
}
