INSERT INTO MTX.MTXTB023_PARAMETRO_SISTEMA (NU_PARAMETRO_SISTEMA, NO_PARAMETRO_SISTEMA, DE_CONTEUDO_PARAMETRO, DH_ATUALIZACAO_PARAMETRO) VALUES (19, 'DATA_BASE_ATUAL_FATOR_VENCIMENTO', '07/10/1997', SYSDATE);
INSERT INTO MTX.MTXTB023_PARAMETRO_SISTEMA (NU_PARAMETRO_SISTEMA, NO_PARAMETRO_SISTEMA, DE_CONTEUDO_PARAMETRO, DH_ATUALIZACAO_PARAMETRO) VALUES (20, 'DATA_BASE_NOVA_FATOR_VENCIMENTO', '29/05/2022', SYSDATE);
INSERT INTO MTX.MTXTB023_PARAMETRO_SISTEMA (NU_PARAMETRO_SISTEMA, NO_PARAMETRO_SISTEMA, DE_CONTEUDO_PARAMETRO, DH_ATUALIZACAO_PARAMETRO) VALUES (21, 'RANGE_VENCIDO_FATOR_VENCIMENTO', '3000', SYSDATE);
INSERT INTO MTX.MTXTB023_PARAMETRO_SISTEMA (NU_PARAMETRO_SISTEMA, NO_PARAMETRO_SISTEMA, DE_CONTEUDO_PARAMETRO, DH_ATUALIZACAO_PARAMETRO) VALUES (22, 'RANGE_A_VENCER_FATOR_VENCIMENTO', '5500', SYSDATE);


commit;
