/*******************************************************************************
 * Copyright (C)  2017 - CAIXA Econômica Federal 
 * 
 * Todos os direitos reservados
 ******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.04 at 05:50:06 PM BRST 
//


package br.gov.caixa.simtx.persistencia.vo;

import java.math.BigInteger;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Header complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Header">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="VERSAOMENSAGEM">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}positiveInteger">
 *               &lt;totalDigits value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="CODIGOCANAL">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}positiveInteger">
 *               &lt;totalDigits value="4"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="CODIGOSERVICO">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}positiveInteger">
 *               &lt;totalDigits value="6"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="VERSAOSERVICO">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}positiveInteger">
 *               &lt;totalDigits value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="NSUCANAL">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}positiveInteger">
 *               &lt;totalDigits value="12"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="DATAREQUISICAO">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;pattern value="[0,3][0-9]/[1][0-9]/[1-9][0-9][0-9][0-9]"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="HORAREQUISICAO">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;pattern value="[0-2][0-9]:[0-6][0-9]:[0-6][0-9]"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="DATACONTABIL" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;pattern value="[0,3][0-9]/[1][0-9]/[1-9][0-9][0-9][0-9]"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="HORACONTABIL" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;pattern value="[0-2][0-9]:[0-6][0-9]:[0-6][0-9]"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="OPERADOR" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;length value="8"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="TERMINAL" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;length value="8"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Header", propOrder = {

})
@XmlRootElement(name = "header")
public class Header {

	@XmlElement(name = "NSUMTX")
    protected Long nsumtx;
    @XmlElement(name = "VERSAOMENSAGEM", required = true)
    protected BigInteger versaomensagem;
    @XmlElement(name = "CODIGOCANAL", required = true)
    protected BigInteger codigocanal;
    @XmlElement(name = "CODIGOSERVICO", required = true)
    protected BigInteger codigoservico;
    @XmlElement(name = "VERSAOSERVICO", required = true)
    protected BigInteger versaoservico;
    @XmlElement(name = "NSUCANAL", required = true)
    protected BigInteger nsucanal;
    @XmlElement(name = "DATA_TRANSACAO_CANAL", required = true)
    protected String datatransacaocanal;
    @XmlElement(name = "HORA_TRANSACAO_CANAL", required = true)
    protected String horatransacaocanal;
    @XmlElement(name = "DATA_CONTABIL")
    protected String datacontabil;
    @XmlElement(name = "DATA_REFERENCIA", required = true)
    protected String datareferencia;
    @XmlElement(name = "TERMINAL")
    protected String terminal;
    
    /**
     * Gets the value of the nsumtx property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getNSUMTX() {
        return nsumtx;
    }

    /**
     * Sets the value of the nsumtx property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setNSUMTX(Long value) {
        this.nsumtx = value;
    }

    /**
     * Gets the value of the versaomensagem property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getVERSAOMENSAGEM() {
        return versaomensagem;
    }

    /**
     * Sets the value of the versaomensagem property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setVERSAOMENSAGEM(BigInteger value) {
        this.versaomensagem = value;
    }

    /**
     * Gets the value of the codigocanal property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCODIGOCANAL() {
        return codigocanal;
    }

    /**
     * Sets the value of the codigocanal property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCODIGOCANAL(BigInteger value) {
        this.codigocanal = value;
    }

    /**
     * Gets the value of the codigoservico property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCODIGOSERVICO() {
        return codigoservico;
    }

    /**
     * Sets the value of the codigoservico property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCODIGOSERVICO(BigInteger value) {
        this.codigoservico = value;
    }

    /**
     * Gets the value of the versaoservico property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getVERSAOSERVICO() {
        return versaoservico;
    }

    /**
     * Sets the value of the versaoservico property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setVERSAOSERVICO(BigInteger value) {
        this.versaoservico = value;
    }

    /**
     * Gets the value of the nsucanal property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNSUCANAL() {
        return nsucanal;
    }

    /**
     * Sets the value of the nsucanal property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNSUCANAL(BigInteger value) {
        this.nsucanal = value;
    }

    /**
     * Gets the value of the datarequisicao property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDATATRANSACAOCANAL() {
        return datatransacaocanal;
    }

    /**
     * Sets the value of the datarequisicao property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDATATRANSACAOCANAL(String value) {
        this.datatransacaocanal = value;
    }

    /**
     * Gets the value of the horarequisicao property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHORATRANSACAOCANAL() {
        return horatransacaocanal;
    }

    /**
     * Sets the value of the horarequisicao property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHORATRANSACAOCANAL(String value) {
        this.horatransacaocanal = value;
    }

    /**
     * Gets the value of the datacontabil property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDATACONTABIL() {
        return datacontabil;
    }

    /**
     * Sets the value of the datacontabil property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDATACONTABIL(String value) {
        this.datacontabil = value;
    }

    public String getDATAREFERENCIA() {
		return datareferencia;
	}

	public void setDATAREFERENCIA(String value) {
		this.datareferencia = value;
	}

	/**
     * Gets the value of the terminal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTERMINAL() {
        return terminal;
    }

    /**
     * Sets the value of the terminal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTERMINAL(String value) {
        this.terminal = value;
    }

}
